server:
  port: 7001
  servlet:
    context-path: /product
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd-mall?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
logging:
  level:
    com.dreamcc.ddd.mall: debug
